config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  root to: 'pages#home'
  devise_for :users

  resources :reviews, only: :destroy
  resources :hairdressers, only: [:index, :show] do
    resources :reviews, only: :create
    collection do
      get :search
    end
    resources :bookings, only: [:new, :create, :show, :index, :destroy]
    resources :availabilities, only: [:new, :create]
  end

end

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :hairdresser
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :hairdresser
  validates_presence_of :start_time, :end_time, :date, :user
  validates :hairdresser, uniqueness: { scope: [:date, :start_time, :end_time] }
  # validate :booking_not_in_range
  validate :check_date
  # validates :booking_not_overlap

  private

  # def booking_not_in_range # checks that a new booking is not intersecting with an existing one
    # if Booking.all = all_bookings
      # all_bookings.select do |booking|
      # :start_time.between?(booking.start_time, booking.end_time)
    # end
      # errors.add(:booking, "Test error")
    # end
  # end

  #   if Booking.where(((:hairdresser_id == hairdresser) && (:date == date)) &&
  #    (start_time.between?(:start_time, :end_time) || end_time.between?(:start_time, :end_time))
  #     errors.add(:booking, "Booking already taken")
  #   end
  #   # ensure that the time slot is not taken
  # end

  def check_date
    if date < Date.today
      errors.add(:booking, "Can't book a date in the past")
    end
  end

  # def booking_not_overlap # checks that an existing booking is not within the new booking
  # end

end

app/models/hairdresser.rb
class Hairdresser < ApplicationRecord
  has_attachments :photos, maximum: 3
  belongs_to :user
  has_many :bookings
  has_many :availabilities
  has_many :reviews, dependent: :destroy
  validates :city, :location, :description, presence: true
  validates :user, presence: true

  # call this on booking instance that is created from user
  # def open?
    # booking made in booking form then:

    # retrieves the date the booking wants to be made and converts it into weekday
    # day_of_week = @booking.date.wday
    # gives the start time of the requested booking
    # start_time = @booking.start_time
    # gives the end time of the requested booking
    # end_time = @booking.end_time

    # retrieve hairdresser and its availability
    # hairdresser_chosen = @booking.hairdresser
    # availability = hairdresser_chosen.availability

    # gives working weekday of hairdresser
    # weekday = availability.weekday
    # gives the open time of the hairdresser
    # open_time = availability.open_time
    # gives the closing time of the hairdresser
    # closing_time = availability.closing_time

    # if day_of_week == weekday && (start_time.between?(open_time, closing_time) && end_time.between?(open_time, closing_time))
      # return true
    # else
      # return false
    # end
  #end
  geocoded_by :street
  after_validation :geocode, if: :street_changed?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :hairdresser
  validates :content, length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :hairdresser, dependent: :destroy
  has_many :bookings
  validates_presence_of :first_name, :last_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
  def new
  end

  def create
    @availability = Availability.new(availability_params)
    @availability.save
  end

  private

  def availability_params
    params.require(:availability).permit(:weekday, :open_time, :closing_time, :hairdresser_id)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @hairdresser = Hairdresser.find(params[:hairdresser_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.hairdresser = Hairdresser.find(params[:hairdresser_id])
    @booking.user = current_user
    date = Date.strptime(params[:booking][:date] ,'%m/%d/%y') - 365*2 - 366
    start_time = Time.strptime(params[:booking][:start_time] ,'%H:%M') + 2*60*60
    end_time = Time.strptime(params[:booking][:end_time] ,'%H:%M') + 2*60*60

    @booking.start_time = start_time
    @booking.end_time = end_time

    @booking.date = date

    if @booking.save
      render 'show'
    else
      render 'show'
    end
  end

  def destroy
    booking = Booking.find(params[:id])

    booking.destroy
    redirect_to root
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :start_time, :end_time)
  end
end

app/controllers/hairdressers_controller.rb
class HairdressersController < ApplicationController

  def index
    @hairdressers = Hairdresser.where.not(latitude: nil, longitude: nil)

    @hash = Gmaps4rails.build_markers(@hairdressers) do |hairdresser, marker|
      marker.lat hairdresser.latitude
      marker.lng hairdresser.longitude
      marker.infowindow render_to_string(partial: "/hairdressers/map_box", locals: { hairdresser: hairdresser })
    end
  end
  # def index
  #   @hairdressers = Hairdresser.all
  # end

  def show
    @hairdresser = Hairdresser.find(params[:id])
    @review = Review.new
    @availability = Availability.new

    @hash = Gmaps4rails.build_markers(@hairdresser) do |hairdresser, marker|
      marker.lat hairdresser.latitude
      marker.lng hairdresser.longitude
      marker.infowindow render_to_string(partial: "/hairdressers/map_box", locals: { hairdresser: hairdresser })
    end
  end

  def new
    @hairdresser = Hairdresser.new
  end

  def create
    @hairdresser = Hairdresser.new(hairdresser_params)
    @hairdresser.save
  end

  def search
    if params[:search][:city].blank?
      redirect_to hairdressers_path
    else
      @hairdressers = Hairdresser.where(city: params[:search][:city].capitalize)

      @hash = Gmaps4rails.build_markers(@hairdressers) do |hairdresser, marker|
        marker.lat hairdresser.latitude
        marker.lng hairdresser.longitude
        marker.infowindow render_to_string(partial: "/hairdressers/map_box", locals: { hairdresser: hairdresser })
    end
      render :index
  end
end

private

def hairdresser_params
  params.require(:hairdresser).permit(:description, :city, :location, :photo)
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @hairdresser = Hairdresser.find(params[:hairdresser_id])
    @review = Review.new(review_params)
    @review.hairdresser = @hairdresser
    if @review.save
      respond_to do |format|
        format.html { redirect_to hairdresser_path(@hairdresser) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'hairdressers/show' }
        format.js  # <-- idem
      end
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4 col-xs-offset-4 form-div">
      <h1 class="text-center">Book your hairdresser</h1>
        <%= simple_form_for [@hairdresser, @booking] do |f| %>
      <%= f.input :date, as: :string, input_html: { class: 'datepicker'} %>
       <%= f.input :start_time, as: :string, placeholder: '00:00', input_html:{ id: 'timepicker1'} %>
       <%= f.input :end_time, as: :string, placeholder: '00:00', input_html: { id: 'timepicker2'}%>
       <div class="text-center">
        <%= f.submit :submit, class: "button" %>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/bookings/create.html.erb
<h1>These are your bookings</h1>
<ul>
  <% @bookings.each do |booking| %>
    <li><%= booking %></li>
  <% end %>
</ul>

app/views/bookings/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-xs-offset-2">
      <div class="message">
          <h1>Your bookings</h1>
        <div class="message-name">

          </ul>
        </div>
        <div class="message-body">
          <p>Where: London</p>
          <p>Thank you for booking an appointment with me. when I am available I will contact you as soon as I can to make further arrangements. </p>
        </div>
        <div class="message-status">
          <p class="status pending">Current Status: Pending</p>
          <p class="price">To be determined</p>
          <%= link_to "Book Another Hairdresser", root_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<%= render 'form', booking: @booking %>

app/views/bookings/show.html.erb
<div class="container">
    <div class="row">
      <div class="col-xs-6 col-xs-offset-2">
      <h1>You booked: <%= @booking.hairdresser.user.first_name %> <%= @booking.hairdresser.user.last_name %></h1>
        <p>Where: <%= @booking.hairdresser.city %></p>
        <p>Date: <%= @booking.date %></p>
        <p>Start: <%= @booking.start_time %></p>
        <p>End: <%= @booking.end_time %></h2>
        <p>Thank you for booking an appointment with me. when I am available I will contact you as soon as I can to make further arrangements.</p>
        <p>Current Status: pending</p>
        <p class="btn-btn-primary"><%= link_to "Book Another Hairdresser", root_path %></p>
      </div>
    </div>
</div>

app/views/hairdressers/_hairdresser_carousel.html.erb
<div id="hairdresser-carousel" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner" role="listbox">
  <% unless hairdresser.photos.empty? %>
    <% hairdresser.photos.each_with_index do |photo, index| %>
      <div class="card-image item <%= "active" if index == 0 %>">
        <%= cl_image_tag photo.path, width: 400, height: 300, crop: :fill, opacity: 50, background: "black", class: "d-block img-fluid" %>
      </div>
    <% end %>
  <% end %>
  </div>
</div>

app/views/hairdressers/_map_box.html.erb
<div class="map-card">
  <%= link_to(hairdresser) do %>
  <%= cl_image_tag hairdresser.photos.second.path, width: 400, height: 300, crop: :fit, class: "map-card-user" %>
  <div class="map-box-heading">

    <p><%= hairdresser.user.first_name %> <%= hairdresser.user.last_name %> </p>

  </div>

  <div class="card-description">
    <p><b>Location:</b> </p>
    <p><%= hairdresser.location %></p>
    <p><b>Description:</b></p>
    <p><%= hairdresser.description %></p>
  </div>
  <% end %>
</div>

app/views/hairdressers/index.html.erb
<div class="main-container">
  <div class="container">
    <div class="row">
      <div class="col-xs-8">
        <div class="row">
          <% if action_name == "search" %>
          <h1 class="page-heading">Hairdressers in <%= params[:search][:city].capitalize %></h1>
          <% end %>
          <% @hairdressers.each do |hairdresser| %>
          <div class="col-xs-12 col-sm-6">
           <div class="card">
            <%= render "hairdresser_carousel", hairdresser: hairdresser %>
            <div class="card-image card-avatar">
              <%= link_to(hairdresser) do %>
              <%= cl_image_tag hairdresser.photos.first.path, width: 400, height: 300, crop: :fit, class: "card-user" %>
              <div class="card-hover">
               <div class="card-hairdresser">
                <h2><%= hairdresser.user.first_name %> <%= hairdresser.user.last_name %> </h2>
              </div>
              <div class="card-description">
                <p>
                  <br><b>Location:</b></br> <%= hairdresser.location %>
                </p>
                <p>
                  <br><b>Description:</b></br> <%= hairdresser.description %>
                </p>
              </div>
            </div>
            <% end %>
          </div>
          <div class="card-hairdresser">
            <h2><%= "#{hairdresser.user.try(:first_name)}" + " " +
              "#{hairdresser.user.try(:last_name)}"
              %>
            </h2>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>

  <div id="map" ></div>

  <% content_for(:after_js) do %>
  <script>
    $(document).ready(function() {


      var handler = Gmaps.build('Google');

      var mapOptions = {
                    // How zoomed in you want the map to start at (always required)
                    zoom: 11,

                    // The latitude and longitude to center the map (always required)
                    center: new google.maps.LatLng(40.6700, -73.9400), // New York

                    // How you would like to style the map.
                    // This is where you would paste any style found on Snazzy Maps.
                    styles: [{"featureType":"administrative","elementType":"labels.text.fill","stylers":[{"color":"#444444"}]},{"featureType":"administrative.country","elementType":"geometry.fill","stylers":[{"visibility":"on"}]},{"featureType":"landscape","elementType":"all","stylers":[{"hue":"#ff0000"}]},{"featureType":"poi","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"road","elementType":"all","stylers":[{"saturation":-100},{"lightness":45},{"hue":"#009eff"}]},{"featureType":"road.highway","elementType":"all","stylers":[{"visibility":"simplified"}]},{"featureType":"transit","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"water","elementType":"all","stylers":[{"color":"#5096c0"},{"visibility":"on"}]}]
                };

      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  </script>


  <% end %>
</div>
</div>
</div>

app/views/hairdressers/show.html.erb
<div class="show-container">

  <div class="container">
    <div class="row">

      <div class="col-xs-12 col-sm-3">

        <%= cl_image_tag @hairdresser.photos.second.path, width: 400, height: 300, crop: :fit, class: "hairdresser-img" %>

        <%= link_to "Book this Hairdresser", new_hairdresser_booking_path(@hairdresser), class: "btn btn-primary booking-btn" %>

      </div>


      <div class="col-xs-12 col-sm-5">


        <p class="name-heading"><%= @hairdresser.user.first_name + " " + @hairdresser.user.last_name %></p>

        <p class="hairdresser-location">You can find me in <%= @hairdresser.location %></p>
        <p><%= @hairdresser.city %></p>

        <p class="hairdresser-description">Some more information about myself: </p>
        <p><%= @hairdresser.description %></p>


      </div>

      <!-- <div class="col-xs-12 col-sm-3 booking-calendar"> -->

<!--      month_calendar do |date| %>
     date.day %>
     end %> -->

     <!-- </div> -->


     <div class="col-xs-12 col-sm-4">
       <div id="small-map" ></div>

       <% content_for(:after_js) do %>
       <script>
        $(document).ready(function() {
          var handler = Gmaps.build('Google');
          handler.buildMap({ internal: { id: 'small-map' } }, function() {
            markers = handler.addMarkers(<%= raw @hash.to_json %>);
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();
            if (markers.length == 0) {
              handler.getMap().setZoom(2);
            } else if (markers.length == 1) {
              handler.getMap().setZoom(14);
            }
          });
        });
      </script>
      <% end %>

    </div>

  </div>


  <!--    <h3>Check availability </h3> -->

  <!-- # simple_form_for [@hairdresser, @availability] do |f| %> -->
  <!-- # f.input :weekday, as: :string, input_html: { class: 'datepicker' } %> -->
  <!-- # f.input :open_time, as: :string, input_html: { class: 'datepicker' } %> -->
  <!-- # f.input :closing_time, as: :string, input_html: { class: 'datepicker' } %> -->
  <!-- # f.button :submit %> -->
  <!-- # end %> -->

  <div class="work-samples">
    <div class="row">
      <div class="col-xs-12">
        <h4>Some examples of my work:</h4>
      </div>
    </div>

    <div class="row">

      <div class="col-sm-12 col-lg-4">
        <%= image_tag "blue_hair.png", class: "sample-img"%>
      </div>


      <div class="col-sm-12 col-lg-4">
        <%= image_tag "placeholder_images/2.jpeg", class: "sample-img"%>
      </div>

      <div class="col-sm-12 col-lg-4">
        <%= image_tag "placeholder_images/6.jpeg", class: "sample-img"%>
      </div>

    </div>

  </div>


  <div class="reviews">

    <div class="row">

      <div class="col-xs-12">

        <div class="review-box">

          <h4>Reviews</h4>

          <div id="reviews">
            <% if @hairdresser.reviews.blank? %>
            Be the first to leave a review for <%= @hairdresser.user.first_name + " " + @hairdresser.user.last_name %>
            <% else %>
            <% @hairdresser.reviews.each do |review| %>
            <p data-review-id="<%= review.id %>">
              <%= render 'reviews/show', review: review %>
            </p>
            <% end %>
            <% end %>
          </div>

          <%= render 'reviews/form', hairdresser: @hairdresser, review: @review %>

        </div>

      </div>

    </div>

  </div>

</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="<%= image_path("favicon.png") %>" rel="shortcut icon" />
    <title>Hairswish</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="main">
      <%= yield %>
    </div>
     <%= render 'shared/footer' %>

    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>


    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(90deg, rgba(39, 38, 55, 0.5) 0%, rgba(71, 65, 104, 0.5) 100%), url('<%= image_path 'banner-image.jpg' %>');">
  <div class="banner-content">
    <h1>FIND A HAIRDRESSER IN YOUR CITY</h1>
    <p>You can forget about bad hair days</p>
    <%= render 'shared/searchbar' %>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for([ hairdresser, review ], remote: true) do |form| %>
  <%= form.input :content, as: :text %>
  <%= form.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/reviews/_show.html.erb
<p>
<%= review.content %>
<%= link_to "Delete", review, method: :delete, remote: true, class: "delete-link" %>
</p>

app/views/reviews/create.js.erb
// Here you will write *javascript* that would be executed by the browser
<% if @review.errors.any? %>
  // Render new review form with errors
  $('#new_review').html("<%= j render 'reviews/form', hairdresser: @hairdresser, review: @review %>");
<% else %>
  // Create a paragraph for the new review. But hide it.
  var new_review = $("<%= j render 'reviews/show', review: @review %>").hide();
  // Add it to the DOM, at the end of the existing reviews. It's still hidden.
  $('#reviews').append(new_review);
  // Show the new review with an animation!
  new_review.fadeIn();
  // Reset the form
  $('#new_review').html("<%= j render 'reviews/form', hairdresser: @hairdresser, review: Review.new %>");
<% end %>

app/views/reviews/destroy.js.erb
$('[data-review-id=<%= @review.id %>]').empty();

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i>
  </div>
</div>

app/views/shared/_hairdresser.html.erb
<%= image_tag "placeholder_images/unicorn.png", class: "hairdresser-img" %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
<!--        link_to "Help", "#", class: "navbar-wagon-item navbar-wagon-link" %>
       link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %> -->

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/Kajsie", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<div class="search-bar-wrapper">
   <div class="search">
      <%= simple_form_for :search, url: search_hairdressers_path, method: :get, html: { class: 'form-inline' } do |f| %>
        <div class="search-bar-bundle">
          <%= f.input :city, autofocus: true, placeholder: 'insert a city', label: false, input_html: { class: 'search-bar-input' } %>
          <%= button_tag class: 'search-button' do %>
            <%= fa_icon "search" %>
          <% end %>
        </div>
      <% end %>
   </div>
</div>